version: "3"

services: 
  nginx-web:
    container_name: nginx
    image: nginx:latest
    pull_policy: always
    restart: always
    ports:
      - "5100:80"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "4g"
        reservations:
          cpus: "0.5"
          memory: "1g"
