version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: pg-db2
    ports:
      - "5501:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
